README.md

I found that the Readme was a little confusing in this area and wanted to fill in the gaps.
I think that the way this reads more clearly illustrates that the Gemfile entires, in the listed order, are all that you really need.  By stating the version of Fog and pending version of CarrierWave that this support is introduced in, people can act accordingly.
For those not relying on the Gemfile entries alone, the text describing the require order and place to check their work should help to alleviate further head scratching.
This is inclusive of the discussions in: https://github.com/carrierwaveuploader/carrierwave/pull/1364, https://github.com/carrierwaveuploader/carrierwave/issues/1337, https://github.com/carrierwaveuploader/carrierwave/issues/1381 and https://github.com/fog/fog/issues/2903.

Clarify optimized loading of Fog in Readme

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

When using Fog and AWS and a new file is uploaded and the old file is missing  `content_length` is called on nil, resulting in the inability to upload a new file.
This change updates the `CarrierWave::Storage::Fog` class such that it will not error if this situation occurs and instead return a 0 file size.
It seems that this change could also be made in https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/sanitized_file.rb#L136 by reversing the conditional `(self.size.zero? && ! self.exists?)`, however the change in this PR seemed less invasive.
The error caused by this issue:
````
NoMethodError: undefined method `content_length' for nil:NilClass
from /srv/app/releases/20150213002036/vendor/bundle/ruby/2.1.0/bundler/gems/carrierwave-0033279be9b6/lib/carrierwave/st …
```

Don't error when size is called on a deleted file

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

When an ActiveRecord model is "#dup"ed the mounted carrierwave uploaders retain their reference to the old model.
Gist showing the bug: https://gist.github.com/danielevans/2316c9b07afa7efca92a

Flush mounters on dup of active record model

---

README.md

In aadbe94a525 and some other commits the ```remove_previously_stored_#{column}``` has been changed to an ```after_commit``` callback, trying to keep README up-to-date.

Update README.md for changes to carrierwave activerecord callbacks

---

README.md
carrierwave.gemspec
lib/carrierwave/storage.rb
lib/carrierwave/storage/fog.rb
lib/carrierwave/uploader/configuration.rb

This PR is an attempt to create an easy support for both providers within `fog` and the ones that were already extracted.
Instead of rely on constant definition to load `fog` support, now it depends on a configuration.
If `fog_provider` is not defined `carrierwave` will try to load `fog` completely. If the user has only `fog-aws` on its Gemfile it will fail.
The use won't need to require any `fog` specifics before `carrierwave` anymore because `carrierwave` will do that now.
The optimized loading of fog is not necessary if the user is using an extracted provider and `google` was extracted so i did some changes on `README` reflecting this.
Let me know if i need to change something else or something is wrong.

Improve Fog Loading

---

README.md

As seen on issue #1386. The documentation was indicating a broken way to do so.

Model.attached was nil, using model_attached fixes it.

---

README.md

Some quick README fixes to try to combat issue thrash:
* Add a line clarifying that 1.0.0 is still forthcoming
* Add a line clarifying how to bundle the gem so that the multiple uploader support referenced in the README is available.

Clarify what's necessary for mount_uploaders

---

lib/carrierwave/processing/mime_types.rb
lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb

Mime-types  2.6.1+ has a columnar store that only loads the data that is needed for a drastically reduced memory footprint. cc/ @jeremyevans @halostatue

Decrease Memory footprint

---

lib/carrierwave/storage/fog.rb

`commondatastorage` is a deprecated endpoint, the current [Request URIs](https://cloud.google.com/storage/docs/reference-uris) should be used instead, and `fog-google` is already up to date.
I guess this could be extended to the other providers too.

Change Google's url to the public_url

---

README.md

Multiple file uploads wouldn't work for me until I had the Controller permit the multi-file-upload-attribute, but not simply, yet pointing to an empty array, so I added the fix to the README.

Fixed README for multiple file uploads

---

lib/carrierwave/utilities/uri.rb

While benchmarking my app (using `derailed`), I noticed a an unusual memory usage in the `Carrierwave::Utilities::Uri` module. The action benchmarked is serializing 60 records each containing a field with an uploader that has 3 versions. The memory usage is not critical and this is not a huge gain in performance so merge it if you think the code respect the guideline of the repository :smile: 
Here is my benchmarks results:
allocated memory by gem
-----------------------------------
**Before**
2399180  `carrierwave/lib`
1470695  `activesupport-4.2.0`
1444700  `activerecord-4.2.0`
**After**
1708780  `carrierwave/lib`
1470695  `activesupport-4.2.0`
1444700  `activerecord-4.2.0`
allocated memory by file
-----------------------------------
**Before**
989475 …

Extract UNSAFE regex in utilities uri to reduce memory usage

---

spec/uploader/versions_spec.rb

There is this test in features, but there isn't it in unit tests.
By the way, it failed when I was manipulating with #1672, but unit tests were green.

Add test: .version with nested versions should set the version name for the #versions

---

.gitignore
lib/carrierwave/storage/fog.rb

Hi!
This update allows to pass additional options to Rackspaces `authenticated_url `.
Options are described [here](http://docs.rackspace.com/files/api/v1/cf-devguide/content/TempURL_File_Name_Overrides-d1e213.html).
Corresponding `fog` PR is fog/fog#3665

Passing options to Rackspace authenticated_url

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

This fixes the behaviour of write_#{column}_identifier in order to
accept re-uploading a file after the previous one was removed from
the same Uploader's instance.

[Fix #1594] Reset remove attribute after invoking remove_#{image}

---

README.md

I've found a small typo in README.md. Please review.

Fix typo in callbacks instruction to README.md

---

lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb

BREAKING CHANGE: Allowing non-ASCII filename by default.
This is a rework of #1148 by @yalab.

Allow non-ASCII filename by default. Rework of #1148

---

lib/carrierwave/mounter.rb

Hi all,
I use carrierwave with [Cloudinary uploader](https://github.com/cloudinary/cloudinary_gem) and I'm randomly seeing this error.
undefined method `match' for ["image/upload/v111111/aaaaaaaaaa.png"]:Array
vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/carrier_wave.rb:150 in initialize
vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/carrier_wave.rb:29 in new
vendor/bundle/ruby/2.2.0/gems/cloudinary-1.1.0/lib/cloudinary/carrier_wave.rb:29 in retrieve_from_store!
vendor/bundle/ruby/2.2.0/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/mounter.rb:130 in block in remove_previous
vendor/bundle/ruby/2.2.0/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave/mounter.rb:127 in map
vendor/bundle/ruby/2.2.0/bundler/gems/carrierwave-49fdad1ec6ca/lib/carrierwave …

Retrieve old file using identifier string not changes array itself

---

lib/carrierwave/storage/file.rb
spec/storage/file_spec.rb
spec/support/file_utils_helper.rb

Errno::EMLINK: Too many links @ dir_s_mkdir
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:247 :in `mkdir`
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:247 :in `fu_mkdir`
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:224 :in `block (2 levels) in mkdir_p`
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:222 :in `reverse_each`
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:222 :in `block in mkdir_p`
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:208 :in `each`
/opt/rubies/ruby-2.1.5/lib/ruby/2.1.0/fileutils.rb:208 :in `mkdir_p`
[GEM_ROOT]/gems/carrierwave-0.9.0/lib/carrierwave/sanitized_file.rb:290 :in `mkdir!`
[GEM_ROOT]/gems/carrierwave-0.9.0/lib/carrierwave/sanitized_file.rb:209 :in `copy_to`
[GEM_ROOT]/gems/carrierwave-0.9.0/lib/carrierwave/uploader/cache.rb:131 …

Store::File#cache! will retry after Errno::EMLINK

---

.travis.yml

CI builds against Rails master are currently failing as Rails 5 depends on an unpublished version of Rack.

Allow failures in CI builds against Rails master

---

lib/carrierwave/processing/rmagick.rb

Backport of #1681.
> Requiring `RMagick` is deprecated on RMagick 2.14.0, so use `rmagick` instead.

Backport: Require rmagick first instead of deprecated RMagick

---

README.md
lib/carrierwave/test/matchers.rb
spec/processing/mini_magick_spec.rb
spec/processing/rmagick_spec.rb

Add a test matcher for the `format`.
Could be useful to test that a conversion has happened.
Usage:
```
context 'the thumb format' do
it 'should be JPEG' do
@uploader.thumb.should be_format('JPEG')
end
end
```

Add be_format test matcher

---

CONTRIBUTING.md

I tried to run tests using Ruby 1.8. and failed on `bundle install`: seems that `ruby-filemagic` requires at least 1.9.3 version.
```
Gem::InstallError: ruby-filemagic requires Ruby version >= 1.9.3.
Installing timecop 0.7.1
Installing fission 0.5.0
An error occurred while installing i18n (0.7.0), and Bundler cannot continue.
Make sure that `gem install i18n -v '0.7.0'` succeeds before bundling.
boris@boris-Inspiron-N5040:~/dev/toptal/carrierwave$ gem install i18n -v '0.7.0'
ERROR:  Error installing i18n:
i18n requires Ruby version >= 1.9.3.
boris@boris-laptop:~/dev/toptal/carrierwave$ 
```

Update Ruby version in CONTRIBUTING.md

---

.travis.yml

Since #1754 merge, JRuby builds fails due to the new hash syntax.
See https://travis-ci.org/carrierwaveuploader/carrierwave/jobs/93603851
This is due to JRuby mode. 
`jruby` resolves to 1.7.10 in 1.9 mode and `jruby-head` resolves to the JRuby master branch in 2.1 mode.
As Travis doesn't support d20 and d21 for JRuby (see https://github.com/travis-ci/travis-ci/issues/2432#issuecomment-46647960), using `JRUBY_OPTS` sets the mode to run for JRuby 1.7.
Note that `JRUBY_OPTS` is ignored by `jruby-head`, which uses Ruby 2.2.3 mode (https://travis-ci.org/carrierwaveuploader/carrierwave/jobs/99350211#L212)
I preferred this instead of changing the hash syntax as it matches MRI Ruby minimal requirements for CarrierWave 1.0.0 (Rails 4 and Ruby 2).
I think though we should only support and test …

Fix Travis JRuby modes for JRuby 1.7

---

lib/carrierwave/processing/mini_magick.rb
spec/processing/mini_magick_spec.rb

I think `CarrierWave::MiniMagick#mini_magic_image` method doesn't need to be part of the public API, at least to keep a symmetry between MiniMagick and RMagick processors (more at #1805). 
This method is used by the new public `#width` and `#height` methods (introduced by #1405).
This commit also fixes a typo in the method name (magick instead of magic).
Any thoughts?

Make `CarrierWave::MiniMagick#mini_magic_image` private

---

lib/carrierwave/processing/mini_magick.rb

This method isn't intended to be part of the public API.
It's used internally by the processor to accept `combine_options`
introduced at #1754.

Make `CarrierWave::MiniMagick#append_combine_options` private

---

lib/carrierwave/processing/mini_magick.rb
lib/carrierwave/processing/rmagick.rb
spec/processing/rmagick_spec.rb

This keeps the symmetry with MiniMagick processor where `#width` and
`#height` methods has been introduced by #1405.

Add `#width` and `#height` methods to the RMagick processor

---

features/caching.feature
features/file_storage.feature
features/file_storage_overridden_filename.feature
features/file_storage_overridden_store_dir.feature
features/file_storage_reversing_processor.feature
features/versions_basics.feature
features/versions_nested_versions.feature
features/versions_overridden_filename.feature
features/versions_overriden_store_dir.feature
lib/carrierwave/uploader/cache.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/uploader/cache_spec.rb
spec/uploader/default_url_spec.rb
spec/uploader/download_spec.rb
spec/uploader/extension_blacklist_spec.rb
spec/uploader/extension_whitelist_spec.rb
spec/uploader/file_size_spec.rb
spec/uploader/magic_mime_blacklist_spec.rb
spec/uploader/magic_mime_whitelist_spec.rb
spec/uploader/processing_spec.rb
spec/uploader/proxy_spec.rb
spec/uploader/remove_spec.rb
spec/uploader/store_spec.rb
spec/uploader/url_spec.rb
spec/uploader/versions_spec.rb

Current (in master) version of generate_cache_id is collision-prone: for complex factories with multiple
uploaders we have quite a few flaky specs because of that. Having a counter, this and similar situations, like mentioned [here](https://github.com/carrierwaveuploader/carrierwave/issues/1232), should be resolved completely.

Add counter to cache_id

---

carrierwave.gemspec

This change reflects what is documented on minimal versions requirements (and what is tested in CI) for the 1.0.0 release.
Those requirements has been introduced at 2517d66809472fca9b1d5638eeeb515b351a8602.

Reflect the documented minimum versions requirements in the .gemspec file

---

lib/carrierwave.rb
lib/carrierwave/mounter.rb
lib/carrierwave/processing/rmagick.rb
lib/carrierwave/sanitized_file.rb
lib/carrierwave/uploader/proxy.rb

As CarrierWave already depends on ActiveSupport that brings `try`,
this change helps to improve the code readability avoiding conditionals.

Use `try` instead of `obj.foo if obj.respond_to?(:foo)`

---

features/support/activerecord.rb
spec/orm/activerecord_spec.rb
spec/support/activerecord.rb

Since `spec/support/activerecord.rb` is required in `features/support/activerecord.rb`, duplicated AR config could be avoided (only migrations differs).
`raise_in_transactional_callbacks` should/would be set to `true` not only for Rails 4.2 but >= 4.2.
Related to #1815.

Avoid duplication between RSpec and Cucumber AR support config

---

.travis.yml

With Container based CI, public projects can cache the bundle.
This make the build :speedboat:
https://docs.travis-ci.com/user/caching/#Enabling-Bundler-caching

Enable Bundler caching on Travis

---

carrierwave.gemspec
features/step_definitions/download_steps.rb
features/support/env.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/orm/activerecord_spec.rb
spec/spec_helper.rb
spec/uploader/download_spec.rb

WebMock provides a cleaner API that helps to simplify some specs
examples.
This PR comes as a follow up to this discussion https://github.com/carrierwaveuploader/carrierwave/pull/1824#discussion_r48693179

Replace ShamRack by WebMock in specs

---

carrierwave.gemspec

This removes from the gemspec
- `rubyforge_project` as it's no more a thing
- `date`, `rubygems_version` and `specification_version` as those shouldn't be set as recommended.
See:
http://www.rubydoc.info/github/rubygems/rubygems/Gem%2FSpecification%3Aspecification_version
http://www.rubydoc.info/github/rubygems/rubygems/Gem/Specification#rubygems_version-instance_method
http://www.rubydoc.info/github/rubygems/rubygems/Gem/Specification#date%3D-instance_method

Cleanup the gemspec

---

.travis.yml

Now, a build will finish as soon as a job has failed, or when the only
jobs left allow failures.
This let us have faster builds feedbacks.
Ref: https://blog.travis-ci.com/2013-11-27-fast-finishing-builds/

Set `fast_finish: true` in Travis config

---

README.md
lib/carrierwave/uploader/content_type_blacklist.rb
lib/carrierwave/uploader/content_type_whitelist.rb
lib/carrierwave/uploader/extension_blacklist.rb
lib/carrierwave/uploader/extension_whitelist.rb
spec/uploader/content_type_blacklist_spec.rb
spec/uploader/content_type_whitelist_spec.rb
spec/uploader/extension_blacklist_spec.rb
spec/uploader/extension_whitelist_spec.rb

Writing
```ruby
def content_type_whitelist
[/image\//]
end
```
isn't very convenient or intuitive due to the array.
This PR suggests to let `#content_type_whitelist` and `extension_whitelist` takes either a
string, a regexp, or an array of values (same thing for blacklists).

Make extensions and content types white/blacklists take a string, regexp, or array of values

---

spec/orm/activerecord_spec.rb

It all started when I read @jnicklas comment:
```ruby
```
I tried to make it better :bowtie:
This PR mainly refactor the way AR classes are reset in specs (e18499569792341d7f10665e226a9c1ca3fe0305).
It uses `Object#remove_const` and `Object#const_set` instead of initializing a new `Event{$counter}` before each spec example.
I think we could extract this support code to a separate module to make it even cleaner.
It also uses ShamRack only around a couple of specs examples that needs it, and not for each one.
I tried to reduce nested `before` callbacks in the examples concerned by this change to make those easier to read.
Minor changes:
- Remove unneeded AR config to not include root in JSON
- Replace AR migrations in specs by `ActiveRecord::Base.connection` calls

Refactor AR specs

---

.rubocop.yml

As suggest at #1826, I started a `rubocop.yml` file where we could agree on some defaults.
I'll update it based on your comments/votes.
I intentionally disabled some cops that I don't think are very crucial to the project at the moment.
We could tweak those progressively based on how sticking to a style guide would work well for the contributors and core team 
:dancer: :heart:

Add a `rubocop.yml` file with basic cops enabled

---

.travis.yml
carrierwave.gemspec
gemfiles/rails-3-2-stable.gemfile
gemfiles/rails-4-0-stable.gemfile
gemfiles/rails-4-1-stable.gemfile
spec/compatibility/paperclip_spec.rb
spec/orm/activerecord_spec.rb
spec/spec_helper.rb
spec/support/activerecord.rb

This PR should fix the build for 0.10-stable branch.
It's a first step I hope towards releasing an intermediate version with some backports, before the 1.0 release ✌️.
@thomasfedb I'd be happy to discuss and share some thoughts on the release plan you guys wants to go with.
Fix #1822

Fix 0.10 stable build

---

lib/carrierwave/mount.rb
spec/mount_single_spec.rb

How to reproduce:
```ruby
class Picture < ActiveRecord::Base
mount_uploader :image, ImageUploader
end
pic = Picture.new
pic.image.object_id # => 70317811568320
pic.image.object_id # => 70317821530860
```
First of all, this bug generates new objects every time, and this is definitely not good. Also this affects on actions with uploader. For example:
```ruby
pic = Picture.new
pic.image.retrieve_from_cache!("1454349370-83816-0001-5310/image.jpg")
pic.image.blank? # => true
```

Fix returning a new instance of the uploader on every uploader call

---

features/caching.feature
features/file_storage.feature
features/file_storage_overridden_filename.feature
features/file_storage_overridden_store_dir.feature
features/file_storage_reversing_processor.feature
features/versions_basics.feature
features/versions_nested_versions.feature
features/versions_overridden_filename.feature
features/versions_overriden_store_dir.feature
lib/carrierwave/uploader/cache.rb
spec/mount_spec.rb
spec/uploader/cache_spec.rb

Backport #1797 to 0.11-stable
------------------
Add counter to cache_id
Old version of generate_cache_id was collision-prone: for complex factories with multiple uploaders we had quite a few flaky specs because of that. With a counter, this (and similar situations like https://github.com/carrierwaveuploader/carrierwave/issues/1232) should be resolved completely.

Backport #1797 to 0.11-stable

---

lib/carrierwave/sanitized_file.rb

I have edited some parts to decrease complexity and code duplication.

Modularize SanitizedFile#copy_to and SanitizedFile#move_to

---

carrierwave.gemspec

JSON support is in Ruby since 1.9 so there is no need to have json gem as a dependency.
Inspired by this Rack’s PR https://github.com/rack/rack/pull/1011

Remove json gem

---

CHANGELOG.md

Fixes https://github.com/carrierwaveuploader/carrierwave/issues/1875 so we can have a new stable release. Maybe it is an idea to only merge pull requests with an updated changelog?
Might be a little bit strange that the 0.10-stable branch now contains changes not included in the latest 0.10 release (0.10.0). Should we release two versions (0.10.1 and 0.11.0)? If so, should I backport the updated changelog with the 0.10-stable changes to the 0.10-stable branch as well?

Update CHANGELOG with post-0.10.0 changes

---

lib/carrierwave/storage/fog.rb

When using :AWS or :Google in the configuration file, access the images stored on AWS or Google are very slow. This is because when using :AWS or :Google, this public_url will return nil, and carrierwave will retrive the public_url by a service call.

improve the performance to access AWS and Google

---

spec/sanitized_file_spec.rb

@thomasfedb, as discussed in #1824, here is a sample of what would look like getting the rid of ivars from specs in favor of `let`.
Is this on the right track? Do you want me to do the for the other specs?

Replace instance variables by `let` in `sanitized_file_spec.rb`

---

README.md
lib/carrierwave/version.rb

I was previously pointing to master, which claims to be version
`0.10.0`. Then I realized `0.11.0` had been released so I upgraded the
gem without realizing I was actually downgrading it... :(
Let's fix it and put something in the version number that makes more sense.
I've also updated `0.10.0` references in the README, but I'm not sure about those. They might be right. Let me know and I'll update the PR.

Normalize gem version

---

CHANGELOG.md

Most code on master wasn't released with v0.11.0. I've merged the existing master changelog with [the one from the 0.11-stable branch](https://github.com/carrierwaveuploader/carrierwave/blob/0.11-stable/CHANGELOG.md).

Fix changelog regarding what was in v0.11.0

---

.travis.yml
lib/carrierwave/storage.rb
lib/carrierwave/storage/fog.rb

this way, an app can depend on only for example fog-aws, instead of all 24 fog provider gems.

replaces requiring all of fog with requiring just the supported providers

---

lib/carrierwave/mount.rb

change a simple spelling mistake: significatnt to significant

fixed an simple spelling mistake

---

lib/carrierwave/uploader.rb
lib/carrierwave/uploader/content_type_blacklist.rb
lib/carrierwave/uploader/content_type_whitelist.rb
spec/uploader/callback_spec.rb
spec/uploader/content_type_blacklist_spec.rb
spec/uploader/content_type_whitelist_spec.rb

Backport the content_type_(whitelist|blacklist) functionality to allow mitigation against ImageTragick to actually work.

Backport Content Type checkers to 0.11 (ImageTragick)

---

lib/carrierwave/locale/cs.yml
lib/carrierwave/locale/de.yml
lib/carrierwave/locale/es.yml
lib/carrierwave/locale/fr-CA.yml
lib/carrierwave/locale/ja.yml
lib/carrierwave/locale/nb.yml
lib/carrierwave/locale/nl.yml
lib/carrierwave/locale/pl.yml
lib/carrierwave/locale/pt-BR.yml
lib/carrierwave/locale/pt-PT.yml
lib/carrierwave/locale/ru.yml
lib/carrierwave/locale/sk.yml
lib/carrierwave/locale/tr.yml
lib/carrierwave/locale/zh-CN.yml
lib/carrierwave/locale/zh-TW.yml

Add content type whitelist/blacklist translations, just like [local/el.yml](https://github.com/carrierwaveuploader/carrierwave/blob/b893859067d6aea497809ace68293633e1d64672/lib/carrierwave/locale/el.yml#L9-L10), [en.yml](https://github.com/carrierwaveuploader/carrierwave/blob/b893859067d6aea497809ace68293633e1d64672/lib/carrierwave/locale/en.yml#L9-L10), [id.yml](https://github.com/carrierwaveuploader/carrierwave/blob/b893859067d6aea497809ace68293633e1d64672/lib/carrierwave/locale/id.yml#L9-L10) and [fr.yml](https://github.com/carrierwaveuploader/carrierwave/blob/b893859067d6aea497809ace68293633e1d64672/lib/carrierwave/locale/fr.yml#L9-L10).

Add content type whitelist/blacklist translations

---

lib/carrierwave/sanitized_file.rb

in order to avoid annoying console deprecation output
```
/home/tomi/.rvm/gems/ruby-2.2.4@copy_carrierwave_file/gems/carrierwave-0.11.2/lib/carrierwave/sanitized_file.rb:146: warning: File.exists? is a deprecated name, use File.exist? instead
/home/tomi/.rvm/gems/ruby-2.2.4@copy_carrierwave_file/gems/carrierwave-0.11.2/lib/carrierwave/mount.rb:243: warning: instance variable @previous_model_for_file not initialized
/home/tomi/.rvm/gems/ruby-2.2.4@copy_carrierwave_file/gems/carrierwave-0.11.2/lib/carrierwave/sanitized_file.rb:146: warning: File.exists? is a deprecated name, use File.exist? instead
/home/tomi/.rvm/gems/ruby-2.2.4@copy_carrierwave_file/gems/carrierwave-0.11.2/lib/carrierwave/sanitized_file.rb:146: warning: File.exists? is a deprecated name, use File.exist? instead
```
gaaah …

use File.exist? not File.exists? as it's depricated

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Related to https://github.com/carrierwaveuploader/carrierwave/pull/1561
Same problem, with `content_type`.

Don't raise an error when content_type is called on a deleted file

---

lib/carrierwave/sanitized_file.rb

Fixes bug where file handles are being left open. This was introduced in #1934
and #1936

Close file in SanitizedFile#mime_magic_content_type

---

README.md

When using `config.fog_provider = 'fog-google'`
I encountered an exception said : LoadError: cannot load such file -- fog-google
Solved this with `config.fog_provider = 'fog/google'`

Fix typo in Google Storage for Developers session

---

README.md

There aren't too many (non-dev/non-test) dependencies in Carrierwave, but I still I ran a scan for compatibility with MIT and all the included gems check out as compatible.
The badge here gives a quick indicator that the license is MIT, and that the libraries used are compliant with that.

Add MIT license badge to the README

---

lib/carrierwave/mount.rb
lib/carrierwave/mounter.rb
lib/carrierwave/uploader/download.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/orm/activerecord_spec.rb
spec/uploader/download_spec.rb

Hi. I use CarrierWave in my project, where I need to download some images using authorization token in header. I haven't found support of sending custom headers in request, so I've implement it in this pull request.
Here is the example of usage:
```ruby
class Content
extend CarrierWave::Mount
mount_uploader :image, ImageUploader
end
c = Content.new
c.remote_image_request_header = {'Authorization' => 'Bearer QWERTY'}
c.remote_image_url = 'http://example.com/1.jpg'
```

Headers for download by url

---

.travis.yml
gemfiles/rails-5-0-stable.gemfile

Fixes #2021.
Currently only Rails master is tested, which is now the development version of 5.1. This adds 5.0 to the test matrix.

Add Rails 5.0 stable gemfile for testing.

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Hiya!
As I understand it, the `public_url` method on the Storage class is intended to return a URL without requiring a GET to the backend. At the moment this is how it works for AWS, but for Google Storage the `directory.files.get` call will make an HTTP request.
I've modified this to use the public access URL as [per Google's documentation](https://cloud.google.com/storage/docs/access-public-data). 
I've also added a very simple spec that's similar to the AWS-specific ones. 
Hope this is helpful!
Nik

Avoids a GET for Google Cloud storage public_urls

---

lib/carrierwave/storage/file.rb
lib/carrierwave/storage/fog.rb
spec/storage/file_spec.rb
spec/storage/fog_helper.rb

Hello, I found bug in `clean_cache!` method.
`CarrierWave::Storage::File.clean_cache!` always cleans all file caches before expired.
Because `CarrierWave::Storage::File.clean_cache!` doesn't refer TIMEINT but PID.
`CarrierWave::Uploader::Cache.generate_cache_id` returns key format like "TIMEINT-PID-COUNTER-RND".
It should refer 1st element(TIMEINT).
But `CarrierWave::Storage::File.clean_cache!` try match `/(\d+)-\d+-\d+$/` .
So it matched 2nd element(PID) which shows the time when cache directory created.
And `Time.at(*time)` always returns like `1970/mm/dd`, then cache directory is all expired.

Fixed bug with the difference of key format between generate_cache_id and clean_cache!

---

lib/carrierwave/test/matchers.rb

(over v0.11.2 while keeping the negative_failure_message method available for older builds)

attempt to solve the negative_failure_message rspec warnings

---

lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb
spec/storage/fog_helper.rb

There has been a longstanding issue in `SanitizedFile#move_to` where an existing content type would be lost. This was exacerbated by the changes in #1312, which made the file cache store use `move_to` all the time.
Prior to this fix, anyone using the file cache store will lose any explicitly set content type. This can be seen in: #1841.
This PR solves the underlying `SanitizedFile` issue, and adds some specs to ensure the same issue isn't present in the fog storage.

Fix content type being reset when using file cache storage

---

lib/generators/templates/uploader.rb

README says `def default_url(*args)` instead of `def default_url`

Fix args of `default_url` in templates

---

README.md

With fog "\~> 1.3.1", there is compatible versions issue for nokogiri if using capybara (2.11.0), fog (\~> 1.3.1) and rails (>= 5.0.0.1, \~> 5.0.0) with `bundler`.
Exemple after a `bundle install`:
```
Bundler could not find compatible versions for gem "nokogiri":
In Gemfile:
capybara was resolved to 2.11.0, which depends on
nokogiri (>= 1.3.3)
fog (~> 1.3.1) was resolved to 1.3.1, which depends on
nokogiri (~> 1.5.0)
rails (>= 5.0.0.1, ~> 5.0.0) was resolved to 5.0.0.1, which depends on
actionpack (= 5.0.0.1) was resolved to 5.0.0.1, which depends on
rails-dom-testing (~> 2.0) was resolved to 2.0.0, which depends on
nokogiri (~> 1.6.0)
capybara was resolved to 2.11.0, which depends on
xpath (~> 2.0) was resolved to 2.0.0, which depends on
nokogiri (~> 1.3)
```
My `Gemfile`: …

Update README: remove version specifier for fog

---

lib/carrierwave/uploader/url.rb

Since `file.url` does somewhat costly operations, we should avoid calling it twice. More aggressive caching may be possible, but this is an easy and straightforward win.

Optimization: avoid calling `file.url` twice.

---

lib/carrierwave/uploader/cache.rb
spec/uploader/cache_spec.rb

Fix for #1889 adjusted regex to allow for negative time stamps.

Fixing #1889 Cache ID should not fail from negative time stamp

---

lib/carrierwave/processing/mini_magick.rb
spec/processing/mini_magick_spec.rb

When a non-argument option is passed to mini magick processing using combine_options, the processing fails.
For example:
```
resize_to_fill(320, 320, combine_options: {strip: nil})
```
generates this command:
```
mogrify -resize 320 -gravity Center -background rgba(255,255,255,0.0) -strip  /var/folders/1_/tdx0fnfx32g1hqv94s3ttkw00000gn/T/mini_magick20170113-86521-eezfq7.jpg
```
But processing is failing with mini_magick_processing_error. Changing `strip: nil` to `strip: ""` (empty string) also did not solve the problem.
The only way I can get it to work is by changing the [append_combine_options](https://github.com/carrierwaveuploader/carrierwave/blob/master/lib/carrierwave/processing/mini_magick.rb#L313) method to invoke the method without any arguments if nil options is passed:
```
def …
```

Allow non-argument options to be passed in mini magick combine_options

---

lib/carrierwave/storage/fog.rb
lib/carrierwave/uploader/configuration.rb
spec/storage/fog_helper.rb

AWS S3 supports accelerated file transfers to and from S3.
[Transfer Acceleration](http://amzn.to/2jQmpAX)
This introduces ability to configure Carrierwave to return
accelerated public urls since Carrierwave constructs them
by itself for speed concerns.
To enable this feauture you need to set fog_aws_accelerate
to true. It is false by default.
Changes added:
* fog_aws_accelerate added to fog aws configuration options
* corresponding specs updated
* corresponding docs updated

Added fog_aws_accelerate options for fog storage provider

---

lib/carrierwave/processing/mini_magick.rb
lib/carrierwave/processing/rmagick.rb
spec/processing/mini_magick_spec.rb
spec/processing/rmagick_spec.rb
spec/spec_helper.rb

Fixing #1977 Invalid locale in CarrierWave::MiniMagick#manipulate!
Since ([commit on May 9, 2014](https://github.com/svenfuchs/i18n/commit/b5703d7431ecfc1b99409e16c6590448570718ac)) enforce_available_locales in I18n is true by default, the aproach which implies on default error messages from `:en` locale is broked for all apps where `:en` is not available locale. It's very suddenly when image processing raise `I18n::InvalidLocale` error.
In this pull request I propose to remove the "default fallback" and let carrierwave users decide themselves how to deal with missed locales and/or translations.

Fixing #1977 Invalid locale in CarrierWave::MiniMagick#manipulate!

---

lib/carrierwave/uploader/processing.rb

This PR adds support to running callbacks before and after proccessing a file. The original motivation was to help adding another mitigation tool for exploits that haunt ImageMagick, like this one: https://www.exploit-db.com/exploits/39767/
Some help to writing proper tests would be appreciated, but no other callbacks are tested specifically, and it was tested manually.

Add support for callbacks on :proccess

---

lib/carrierwave/mount.rb

Firstly thanks for a great gem! This is my first PR, so hopefully I'm on the right lines here.
Rails 5.1.0 introduces deprecation warnings for methods around dirty attributes in ActiveRecord as outlined here: https://github.com/rails/rails/commit/16ae3db5a5c6a08383b974ae6c96faac5b4a3c81
This PR fixes the deprecation warnings by switching the dirty attribute method used, based on the ActiveRecord version in use.

Fix Rails 5.1.0 deprecation warnings

---

lib/carrierwave/mounter.rb

The PR I raised: https://github.com/carrierwaveuploader/carrierwave/pull/2130 successfully removed the deprecation warnings but unfortunately introduced a regression.
Rails 5.1.0 `saved_changes` behaves differently to `changes`: it returns the previous non existent change for the images column as nil instead of an empty array.
`saved_changes` returns:
```
{"id"=>[nil, 1], "images"=>[nil, ["test.jpeg"]]}
```
whereas `changes` returns:
```ruby
{
"id"=>[nil, 1],
"images"=>
[[],
[#<#<Class:0x00000003dbe158>:0x0000000322a828
@cache_id=nil,
@cache_storage=#<CarrierWave::Storage::File:0x0000000321cbd8 @uploader=#<#<Class:0x00000003dbe158>:0x0000000322a828 ...>>,
@file=#<CarrierWave::SanitizedFile:0x000000028dfd90 @content_type="image/jpeg", @file="/app/spec/public/uploads/test.jpeg", …
```

Fix 5.1.0 regression from using `saved_changes` instead of `changes`

---

README.md

I clicked on the link in the readme and got really confused when I saw a bunch of questions about ASP.net. I propose that the readme links to the `carrierwave` tag on Stack Overflow.
Thoughts?

Link to CarrierWave questions on Stack Overflow

---

README.md

After a lot of attempts, only this example works for me.
Syntax is taken from fog: https://github.com/fog/fog-google/blob/db446d1d8fbf0b75e13b4c39af3eb6b1ecb3101c/lib/fog/storage/google_json/models/file.rb
and tested for fog-google, and fog-aws.

Correct syntax in README

---

lib/carrierwave/orm/activerecord.rb
lib/carrierwave/validations/active_model.rb

Right now if a user overrides the `send` method in their model it breaks the mount_upload helper and carrierwave validations. By using `__send__` instead it avoids possible name clashes for when the user does override `send` in their model.

Replace send with __send__

---

README.md

There was a minor typo in the 'versions' example of the README.

Fixed minor typo in README under 'versions' section

---

lib/carrierwave/uploader/extension_whitelist.rb
spec/uploader/extension_whitelist_spec.rb

https://github.com/carrierwaveuploader/carrierwave/issues/2177

Case Sensitive Issue In Regex

---

lib/carrierwave/uploader/file_size.rb
spec/uploader/file_size_spec.rb

**before**
`File size should be less than 1234567`
**after**
`File size should be less than 1.18 MB`

Change file size of error message to human size

---

lib/carrierwave/processing/mini_magick.rb
lib/carrierwave/processing/rmagick.rb
spec/processing/mini_magick_spec.rb
spec/processing/rmagick_spec.rb

I opened this issue (https://github.com/carrierwaveuploader/carrierwave/issues/2167) earlier this week and found a couple hacky solutions, so I thought I'd offer a more direct solution.
I then found this issue (https://github.com/carrierwaveuploader/carrierwave/issues/464) today and I think my fix would solve that problem as well, but may need to be updated to include something like [this](https://github.com/carrierwaveuploader/carrierwave/blob/540a84c606353a878d6574740e44f7970b754463/lib/carrierwave/uploader/configuration.rb#L150) in case some context needs to be passed in.
Let me know what you think! Thanks,
Tom

Added Proc Support for Width and Height

---

lib/carrierwave/utilities/uri.rb

otherwise raises: `uninitialized constant CarrierWave::Utilities::Uri::URI (NameError)` on a dependent project: https://github.com/metaware/carrierwave-google-storage

add require statement

---

lib/carrierwave/uploader/configuration.rb

Instead of passing string to `instance_variable_defined?`, we pass a symbol, which saves
an allocation and on micro benchmarks it's faster.

Reducing allocations while reading configuration

---

lib/carrierwave/storage/fog.rb

When you check if a file exists using Fog, you can potentially end up with an extra HEAD request to the remote server: one request to check its existence and another to read the file.
Consider the following code:
```
if fog_file.exists?
fog_file.read
end
```
It will produce two HEAD request and one GET
With this PR, it will produce only one HEAD and one GET.

Remove potentially redundant HEAD request

---

lib/carrierwave/processing/mini_magick.rb
lib/carrierwave/processing/rmagick.rb
lib/carrierwave/sanitized_file.rb
spec/processing/mini_magick_spec.rb
spec/processing/rmagick_spec.rb
spec/sanitized_file_spec.rb

Hi.
The original Content-Type is preserved, although the file format has been converted. 
It is a problem in my application, which returns the Content-Type by extracting from the stored file.
I would be happy if the Content-Type is set again with a converted new file.

Reset Content-Type when converting a file format

---

lib/generators/templates/uploader.rb

Removed unwanted space from uploader template which was causing overcommit error.

Remove unwanted space from uploader template

---

README.md

Hi there! 
Right now Carrierwave's latest version is 1.2.2. 
The `gem install` instruction seems to be out of date. 
Please check it out.
Thanks!

Update `gem install carrierwave` instruction in README

---

lib/carrierwave/storage/fog.rb
spec/fixtures/new_dir/gurr.png
spec/storage/fog_helper.rb

Hi from GitLab.
We're currently having [a problem](https://gitlab.com/gitlab-org/gitlab-ce/issues/46182) because Carrierwave eagerly loads large files into memory. This was originally fixed at https://github.com/carrierwaveuploader/carrierwave/pull/468, but reproduced at https://github.com/carrierwaveuploader/carrierwave/pull/1517.
I fixed by adding a logic to reopen closed streams when `::Fog#read` is kicked. This shouldn't affect Carrierwave performance, nor breaking https://github.com/carrierwaveuploader/carrierwave/pull/1517 changes.
Just in case, I added a test to check that CW works even if the file is `StringIO`, i.e. `new_file.read` path.
/cc

Fix CarrierWave reads large files into memory

---

README.md

Good AWS practice dictates we should be using instance profiles where possible for AWS s3 permissions (provided we are all within AWS land).  I had to go digging to find this parameter, so upgraded the documentation to make it easier for anyone looking for this in future.

Add `use_iam_profile` aws config parameter

---

README.md

@plribeiro3000 - saw your comment on https://github.com/fog/fog/pull/4001 and that you're a maintainer here, so thought I'd put together a badge for carrierware, too 🙂.
I've also fixed the codeclimate badge. ~~I left the git.legal badge, which was broken when I was putting this together, incase they were just suffering downtime. I'll delete it if they're not back up tomorrow...~~ I've now deleted the git.legal badge, too.
Updated badges:
[![Build Status](https://travis-ci.org/carrierwaveuploader/carrierwave.svg?branch=master)](http://travis-ci.org/carrierwaveuploader/carrierwave) [![Code Climate](https://codeclimate.com/github/carrierwaveuploader/carrierwave.svg)](https://codeclimate.com/github/carrierwaveuploader/carrierwave) [![SemVer](https://api.dependabot.com/badges/compatibility_scor …

Add SemVer stability badge to README, and fix code climate badge

---

lib/carrierwave/storage/file.rb
spec/storage/file_spec.rb
spec/support/file_utils_helper.rb

Hi from GitLab
Currently, we're experiencing that Carrierwave raises `Errno::ENOSPC` when caching files. This is because inodes are full in the cache directory regardless of that its capacity has still some room. (See more  https://gitlab.com/gitlab-com/gl-infra/infrastructure/issues/5217) We manually removed old cache files/directories and the situation was mitigated, but this could happen in the future again, and ideally this recovery process should be automated.
/cc @stanhu

If no space left then remove old cache

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Even in AWS S3 compatibility mode, Google now appears to reject requests
that includes this header with this error:
```
Requests cannot specify both x-amz and x-goog headers
```

Only include `x-amz-acl` header for AWS

---

spec/sanitized_file_spec.rb

Leftover `new_dir` directories with the wrong permissions were causing
false positives when multiple examples were running.

Fix failing master builds

---

lib/carrierwave.rb

This pull request adds [Jets](http://rubyonjets.com/) support to Carrierwave as a [Turbine](http://rubyonjets.com/docs/jets-turbines/). Jets is a Ruby Serverless Framework. This allows us to upload files to s3 via Carrierwave with API Gateway and AWS Lambda. Here are some relevant links:
* [Live Demo of Jets Support Working](https://upload.demo.rubyonjets.com/)
* Blog Post covering it: [Jets Image Upload Carrierwave Tutorial: Binary Support](https://blog.boltops.com/2018/12/13/jets-image-upload-carrierwave-tutorial-binary-support)

Add Jets Turbine Support

---

carrierwave.gemspec
lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

This requires https://github.com/fog/fog-google/pull/409/files

Add query parameter support for fog-google

---

lib/carrierwave/processing/mini_magick.rb
spec/orm/activerecord_spec.rb
spec/processing/mini_magick_spec.rb

Fixes #1947 and the issue described in #2299 
> When a file is uploaded and it is still not saved yet, getting its width or height fails with an error message something like in #1947. So this fix uses the cached file first if it is available or use previous strategy to continue.

MiniMagick: use read method to get file data

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

This brings over the functionality from [fog](https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L285-L288) that avoids using the aws subdomain when https and the bucket has periods in it.  I had to update the tests for `assets.site.com` because this also falls victim to the same [bug that I encountered](https://github.com/carrierwaveuploader/carrierwave/issues/2354).
```
-> % curl https://assets.site.com.s3.amazonaws.com
curl: (51) SSL: certificate subject name (*.s3.amazonaws.com) does not match target host name 'assets.site.com.s3.amazonaws.com'
```

Fix issue with subdomains and buckets with periods

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Adds `authenticated_url` support when using [fog-azure-rm](https://github.com/fog/fog-azure-rm)

Add support AzureRM provider to authenticated_url

---

lib/carrierwave/storage/fog.rb

The options parameter has been supported all along in OpenStack. This
may be needed to talk to servers that are configured on non-standard
ports.

Pass OpenStack options in get_object_https_url

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

When we try to create new active record object into transaction and meet rollback:
database row will not be created but uploader has created file in folder and doesn't remove it.
I changed behavior: now we store file only after commit action. This true and for update action in transaction.
Changes in spec/orm/activerecord_spec.rb:
- Add tests which covers this flows
- replace cleaning folder from 'file_path' to 'public_path'. Cause file_path is 'spec/fixtures'
and we don't create any 'uploads' folders there. We works with 'spec/public/uploads' folder.

Manage transaction rollback

---

lib/carrierwave/sanitized_file.rb
spec/fixtures/spoof.png
spec/sanitized_file_spec.rb
spec/spec_helper.rb
spec/storage/fog_helper.rb
spec/uploader/proxy_spec.rb

This fixes an issue raised in https://github.com/carrierwaveuploader/carrierwave/pull/1934, where a malicious user could bypass the stricter mime-type checking by choosing header bytes that are not recognized by the `mimemagic` gem.

Do not allow file type spoofing if the header bytes are not recognized

---

README.md
lib/carrierwave/uploader/versions.rb
spec/uploader/versions_spec.rb

Fixes #1164. Maybe it's also related to #1602.

regard :from_version option on calling #recreate_versions! with args

---

lib/carrierwave/uploader/configuration.rb

Create a setup using this wiki https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Define-different-storage-configuration-for-each-Uploader leads to initializing CarrierWave on every uploader initialization instead of using cached connections.
This PR adds connection cache utilization for the case described in wiki above.

Preserve connection cache when setting fog_credentials

---

lib/carrierwave/uploader/serialization.rb

`> uploader.as_json`
Before: 
```
{
"url" => "/uploads/81445456.jpg", 
:thumb => {
"url" => "/uploads/thumb_81445456.jpg"
}
}
```
After: 
```
{
"url" => "/uploads/81445456.jpg", 
"thumb" => {
"url" => "/uploads/thumb_81445456.jpg"
}
}
```

Fix #serializable_hash to returns string keys for versions

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Background:
- it is weird when calling file.content_type return `false` if file is deleted
- I would expecting a string (or maybe nil) for file.content_type

Do not return unexpected false for content type when file is deleted

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Adds authenticated_url support when using [fog-aliyun](https://github.com/fog/fog-aliyun)

Add support Aliyun provider to authenticated_url aliyun

---

README.md

We struggled to make carrierwave work with S3 (with iam profile) only to found out that we needed to add the `s3:PutObjectAcl` permission to the role used. This note in the documentation may save a lot of time for future developers setting up S3 with carrierwave. 
The listed permissions are the ones we are currently using. If Carrierwave actually needs more permissions (or doesn't need one of the listed in the changes) let me know and I can change the PR. English is not my native language, so feel free to make any corrections needed.

Add note on S3 permissions on the 'Using Amazon S3' section

---

README.md
lib/carrierwave/mount.rb
lib/carrierwave/mounter.rb
lib/carrierwave/uploader/cache.rb
lib/carrierwave/uploader/mountable.rb
lib/carrierwave/uploader/store.rb
lib/carrierwave/validations/active_model.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/uploader/mountable_spec.rb

Rework multiple file upload

---

lib/carrierwave/downloader/remote_file.rb
spec/downloader/remote_file_spec.rb

Fix `remote_x_url=` when the response header includes `content-disposition: inline;filename=""`
Please see https://github.com/carrierwaveuploader/carrierwave/issues/2411#issuecomment-529735994 for detail.
Maybe related to #2415 also.

Fix `remote_x_url=` raise undefined method `[]' for nil:NilClass (NoMethodError)

---

lib/carrierwave/processing/mini_magick.rb

Prevents `uninitialized constant CarrierWave::MiniMagick::Image` errors

Make MiniMagick::Image constant absolute

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

https://github.com/carrierwaveuploader/carrierwave/pull/2359 added support for bucket names with period, but this only works for `us-east-1` region. For other regions `s3.{aws-region}.amazonaws.com` needs to be used (see https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro).
This PR adds support for bucket names with period that are placed in regions other than `us-east-1`.
---
Also, I'm wondering about one other thing regarding virtual-hosted–style URL. https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html#access-bucket-intro says:
> Buckets created in Regions launched after March 20, 2019 are not reachable via the https://bucket.s3.amazonaws.com naming scheme. 
Should carrierwave be updated to use …

Fix S3 path-style URL for host with dots for buckets that are placed in other regions than us-east-1

---

README.md

The docs currently only demonstrate two processing methods, but mini_magick has five.
I don't want to duplicate too much of the "real" documentation (from `carrierwave/processing/mini_magick.rb`) in the readme, but I do want to give people a list of methods, and tell them where to find said real docs.

Docs: add a complete list of processing methods

---

lib/carrierwave/storage/fog.rb
lib/carrierwave/uploader/cache.rb
spec/storage/fog_helper.rb

To provide support for private objects in Backblaze
https://github.com/fog/fog-backblaze/issues/6

Backblaze private bucket support

---

README.md

The callbacks listed in the README were in a different order to the application code [1].  There was also an after_save which has been changed to an after_commit [2] (albeit only on create or update), which should therefore have the same behaviour but will execute at a different time to an after_save.
[1]: https://github.com/carrierwaveuploader/carrierwave/blob/d12a289d9cdd68d26d3900cf7f1e4e879678d16b/lib/carrierwave/orm/activerecord.rb#L59-L64
[2]: https://github.com/carrierwaveuploader/carrierwave/commit/665f2254a2c70385b67942b13a4710dc6826c42d

Update callbacks in README

---

lib/carrierwave/sanitized_file.rb
lib/carrierwave/uploader/download.rb

This PR fix some deprecation warnings introduced with Ruby 2.7.
- Separation of positional and keyword arguments in Ruby 3.0 [source](https://www.ruby-lang.org/en/news/2019/12/12/separation-of-positional-and-keyword-arguments-in-ruby-3-0/)
- Deprecation of URI.decode [link](https://docs.knapsackpro.com/2020/uri-escape-is-obsolete-percent-encoding-your-query-string)
```
warning: URI.escape is obsolete
warning: URI.encode is obsolete
```
- Deprecation of Kernel.open
```
calling URI.open via Kernel#open is deprecated, call URI.open directly or use URI#open

[1.x-stable] - Fix deprecation warning ruby 2.7

---

README.md

See 
https://github.com/carrierwaveuploader/carrierwave/pull/1879/files#r506082731
https://github.com/carrierwaveuploader/carrierwave/commit/629afecbaeccd2300e4660b78ee36bd95dd845c5#commitcomment-43337716

Update README to indicate when to use :file as the cache storage for AWS

---

lib/carrierwave/uploader/cache.rb
spec/uploader/cache_spec.rb

The document says `cached?` is expected to return `Bool` value. But actually, the method returns a `@cache_id`.
According to the document and ruby basic style, fixes return value to `Bool` value from `@cache_id`.
This change has breaking changes, so perhaps should not be changed this behavior.

Fix return value of `cached?` according to document

---

README.md

The README is a little out of date, updating it:
- Added a newer JSON API config example
- Remove old deps
- `google-api-client` is now required automatically
- `mime-types` is now automatically required by `google-api-client`

Update Google Cloud Storage documentation

---

lib/carrierwave/uploader/content_type_whitelist.rb
spec/fixtures/ruby.svg
spec/uploader/content_type_whitelist_spec.rb

A lot a mimetypes match the following scheme: type/subtype+other.
Carrierwave must allow the validation of these types without error.
This patch is providing the support for theses types, along with the tests to validate it

handle mimetype validation with symbol + (#2488)

---

lib/carrierwave/uploader/url.rb
spec/uploader/url_spec.rb

Hi there,
Currently, the method #url is being called twice (with and without options) in a case of arity != 0 (very common case).
It is very inefficient for signed URLs specifically.
This PR fixes that.
Thanks!

Performance improvement, fixes twice #url method call

---

CHANGELOG.md

The fact that CW 2.0 changes the default of `cache_storage` (in my case from `:file` to `:fog`) was a breaking change for me. I'm not sure what qualifies as "breaking" in CW, but if this had been marked as breaking that would have been helpful to me.

Docs: breaking change: `cache_storage` default

---

lib/carrierwave/uploader/content_type_blacklist.rb
lib/carrierwave/uploader/content_type_whitelist.rb
lib/carrierwave/uploader/extension_blacklist.rb
lib/carrierwave/uploader/extension_whitelist.rb

Prior to this patch every content_type_* filter would parse magic headers via `SanitizedFile#content_type`,
even when the filter was not defined.
I have split the primary conditional check in to a guard clause that
simply returns unless the blacklist or whitelist returns truthy.
I've made the same changes to the extension filters for consistency.
I wanted to remove any unnecessary parse of magic headers completely on upload. This is a half measure to getting there.

Skip content type filters where possible.

---

lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb

Fixes #2424
It also supports this edge case:
I have to deal with text files provided by public administrations with inconsistent extensions ( .N000777, .BATI, .txt, missing extensions) alongside known extensions (.csv, .pdf, images, etc.)
Returning a missing content type is quite different from returning an invalid content type.

Do not return invalid content type on text files

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

When upgrading from carrierwave 1.3 to 2 we noticed that when we upload to GCS the URL we get is not public, even though we have `fog_public = true` in our initializer.
After some investigation it looks like the copy_object is not maintaining the ACL, this change is passing the correct ACL if `fog_public` is true.
Tested locally and it fixed the issue.
Closes https://github.com/carrierwaveuploader/carrierwave/issues/2426
fog-google pr: https://github.com/fog/fog-google/pull/513

GCS: pass acl_header for public read if fog is public

---

lib/carrierwave/uploader/content_type_blacklist.rb
lib/carrierwave/uploader/content_type_whitelist.rb
lib/carrierwave/uploader/extension_blacklist.rb
lib/carrierwave/uploader/extension_whitelist.rb
spec/uploader/content_type_blacklist_spec.rb
spec/uploader/content_type_whitelist_spec.rb
spec/uploader/extension_blacklist_spec.rb
spec/uploader/extension_whitelist_spec.rb

The goal of this pull request is to give developers the option to use something like allowlist/blocklist terminology with this gem instead of whitelist/blacklist. https://github.com/rubocop-hq/rubocop/pull/6464 has links to the original motivation and many changes to other gems that have been replacing those words.
Since managing allowed content types and extensions is a significant part of the gem's purpose and impacts the code users write, as a starting point the changes in this PR are intended to be minimally intrusive. Overriding the existing methods still works so it is backwards compatible. If there is buy-in from the maintainers, I will gladly contribute deeper changes to the internals and deprecation of the old methods could be considered as well.
Allowlist and blocklist are only …

Provide public interface alternatives to whitelist/blacklist terminology

---

.github/workflows/test.yml
carrierwave.gemspec
lib/carrierwave/locale/en.yml
lib/carrierwave/processing.rb
lib/carrierwave/processing/vips.rb
spec/processing/vips_spec.rb
spec/spec_helper.rb

This PR adds support for [libvips](https://github.com/libvips/libvips) through [ImageProcessing::Vips](https://github.com/janko/image_processing) and [ruby-vips](https://github.com/libvips/ruby-vips).
A few notes:
- I had to unlock `rmagick` as it's currently at version 4 and it wouldn't build version 2 on my machine
- I added [pry-byebug](https://github.com/deivid-rodriguez/pry-byebug) to development dependencies which makes stepping through the code infinitely easier via `binding.pry`
- libvips differs from ImageMagick in that [resize_and_pad](https://github.com/janko/image_processing/blob/master/doc/vips.md#resize_and_pad) adds a black background by default, not a white one. The background is transparent if the alpha channel is set and supported.

Add CarrierWave::Vips and related specs

---

lib/carrierwave/sanitized_file.rb
spec/fixtures/addresses.csv
spec/sanitized_file_spec.rb
spec/spec_helper.rb

Resolves https://github.com/carrierwaveuploader/carrierwave/issues/2559
In my previous PR I mistakenly passed the `file` argument to `Marcel::Magic.by_path` instead of `path`. This was not an issue in the majority of cases (`File` objects work properly) but not for a CSV, which raises a `TypeError Exception: no implicit conversion of CSV into String`. Since all tests were passing, this bug passed inadvertently. I added a new test to ensure it does not happen again.

Fix bug when reading content_type from a CSV object linked to a file

---

lib/carrierwave/mount.rb
lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

This prevents accumulating stale files when transaction is aborted.
Depends on #2545 , restores functionality added by #2209

fix: remove uploaded files if transaction is rolled back

---

carrierwave.gemspec
lib/carrierwave/downloader/remote_file.rb
lib/carrierwave/processing/mini_magick.rb
lib/carrierwave/processing/rmagick.rb
lib/carrierwave/processing/vips.rb
lib/carrierwave/sanitized_file.rb
spec/downloader/remote_file_spec.rb

- Replaces `mini_mime` with `marcel` since `marcel` has the same functionality 
- Pros:
- The number of dependencies is reduced (less complexity, less bugs)
- More consistency since mime types and extensions would be handled by a single gem
- `marcel` is maintained by Rails core team, which is a warranty of long-term support and development
- `marcel` identifies 1243 extensions while `mini_mime` identifies 1210
```
irb(main)> Marcel::EXTENSIONS.count
=> 1243
irb(main)> File.readlines(MiniMime::Configuration.ext_db_path).each do |line|
irb(main)*     s << line.strip
irb(main)> end
irb(main)> File.readlines(MiniMime::Configuration.content_type_db_path).each do |line|
irb(main)*     s << line.strip
irb(main)> end
irb(main)> s.length
=> 1210
```
- Cons:
- Introduces the following [breaking …

Replace mini_mime with marcel

---

.github/workflows/test.yml
CONTRIBUTING.md
Gemfile
carrierwave.gemspec
gemfiles/rails-5-0.gemfile
gemfiles/rails-5-1.gemfile
gemfiles/rails-5-2.gemfile
gemfiles/rails-6-0.gemfile
gemfiles/rails-6-1.gemfile
gemfiles/rails-master.gemfile
spec/orm/activerecord_spec.rb
spec/support/activerecord.rb

I removed Postgres service and used In Memory Sqlite3. This change made the test run much faster as they don't depend on other services.

Remove Postgresql and use sqlite3 for testing ActiveRecord

---

CHANGELOG.md
lib/carrierwave.rb

Merb was deprecated in 2010. And dont work with current version of ruby

Remove Support for Merb

---

lib/carrierwave/mounter.rb

The return value changes from an Array to nil.
But it is usually ignored because it is in a setter method.

Remove redundant each after zip in `remote_urls=`

---

lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb

This MR makes CarrierWave skip calling`#close` after upload is `#read` when when such upload it's based on `StringIO` (vs. `File` or other implementations).
Closing `StringIO`-based "files" is:
- Unnecessary as these don't have associated file-handle to worry about (original need via #1040);
- Problematic (causing `IOError: not opened for reading`) for situations when more than one read of upload blob is needed for business/logic reasons.

Don't close StringIO-based file after CarrierWave::SanitizedFile#read

---

README.md
lib/carrierwave/downloader/base.rb
lib/carrierwave/uploader/configuration.rb
spec/downloader/base_spec.rb

Our project downloads image from imgix by use `remote_image_url`, but imgix occasionally returns a 503 error and download failed.
So I want to support to retry option in carrierwave.
This option will also be useful for other CDNs or storage.
Source: https://aws.amazon.com/premiumsupport/knowledge-center/s3-resolve-503-slowdown-throttling/?nc1=h_ls

Add retry option to download from remote url

---

lib/carrierwave/uploader/processing.rb
lib/carrierwave/uploader/versions.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/uploader/processing_spec.rb
spec/uploader/versions_spec.rb

Allows uploaders to accept `unless` conditions in their processor callbacks, previously only `if` conditions were allowed

Allow uploaders to accept unless conditions

---

lib/carrierwave/sanitized_file.rb
lib/carrierwave/storage/fog.rb
lib/carrierwave/uploader/download.rb
lib/carrierwave/version.rb

👋 Dear maintainers,
There is currently a pretty complicated legacy project that I'm working on, however, in the process of ruby upgrade, it's fairly difficult to upgrade from 0.11.x to 1.x due to sheer amount of breaking changes from [CHANGELOG.md](https://github.com/carrierwaveuploader/carrierwave/blob/master/CHANGELOG.md#100beta---2016-09-08). 
Ideally, a more organized migration guide from 0.11.x to 1.x would be awesome.
I have looked into v2 fix https://github.com/carrierwaveuploader/carrierwave/commit/9a37fc9e7ce2937c66d5419ce1943ed114385beb
I'm not sure this change relates to any deprecation and whether it should be backport as well? 🤷 
`remove.present? && (remove == true || remove !~ /\A0|false$\z/)`
Would it be possible to accept this patch similar to …

backport ruby 2.7+ deprecations to 0.11.x

---

lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb

When uploading a file whose filename contains a sequence like `%dd` (e.g. `test%dd.jpg`) it gets treated as a hex-encoded character.
The encoding happens [here inside ActionDispatch::HTTP::UploadedFile](https://github.com/rails/rails/blob/89471b2d7d3e6df631b1c236573c6674ac7f2502/actionpack/lib/action_dispatch/http/upload.rb#L34-L38).  If the hex-encoded character is invalid, Rails calls `@original_filename.force_encoding(Encoding::UTF_8)` and now we have an invalid string that gets passed down as the `original_filename` all the way to Carrierwave.
This PR calls [`String#scrub`](https://ruby-doc.org/core-2.7.2/String.html#method-i-scrub) to strip out any invalid bytes so we can then continue with the normal sanitization logic.

Remove invalid byte sequences from the sanitized filename

---

features/support/env.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/sanitized_file_spec.rb
spec/spec_helper.rb
spec/storage/fog_helper.rb
spec/uploader/cache_spec.rb
spec/uploader/content_type_allowlist_spec.rb
spec/uploader/extension_allowlist_spec.rb
spec/uploader/extension_denylist_spec.rb
spec/uploader/file_size_spec.rb
spec/uploader/url_spec.rb

suppress rspec deprecation warnings
e.g)
```
The implicit block expectation syntax is deprecated, you should pass a block rather than an argument to `expect` to use the provided block expectation matcher or the matcher must implement `supports_value_expectations?`. e.g  `expect { value }.to raise CarrierWave::DownloadError` not `expect(value).to raise CarrierWave::DownloadError`
/home/runner/work/carrierwave/carrierwave/spec/uploader/url_spec.rb:64: warning: already initialized constant FileX
/home/runner/work/carrierwave/carrierwave/spec/uploader/url_spec.rb:64: warning: previous definition of FileX was here
```

suppress some rspec deprecation warning

---

gemfiles/rails-main.gemfile

rails/sprockets already has no master branch.

Fixed non-existent branch name

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_helper.rb

Files lose their correct content type when copied on Google Cloud Storage. For example an SVG file with content type "image/svg+xml" becomes "application/octet-stream" when copied to another path on the same bucket.
Google Storage API only [considers the `:content_type` option](https://github.com/googleapis/google-api-ruby-client/blob/16c46ef4deb499a390effe9d4edd6a5cbba6cf04/generated/google-apis-storage_v1/lib/google/apis/storage_v1/classes.rb#L1635), so `'Content-Type'` as [defined in `copy_options`](https://github.com/carrierwaveuploader/carrierwave/blob/3cfabaf/lib/carrierwave/storage/fog.rb#L490) is ignored.
Set both keys. Beware, I assume that 'Content-Type' is required by AWS but I haven’t checked that.

Set `:content_type` in `copy_options` for GCS.

---

.github/workflows/test.yml
Gemfile
carrierwave.gemspec
lib/carrierwave/downloader/base.rb

Includes a backwards compatibility mode for SsrfFilter 1.0,
which is needed for Ruby 2.5 and JRuby 9.2.
Also includes a local version constraint for fog-google for
Ruby 2.5 and JRuby 9.2 because of a known but undeclared
incompatibility in that gem.
[Fixes #2625]

Support ssrf_filter 1.1

---

lib/carrierwave/uploader/processing.rb

Minor refactor to use performant `Array#detect` vs `Array#select[0]`
```zsh
Warming up --------------------------------------
Enumerable#select.first
17.450k i/100ms
Enumerable#detect    78.375k i/100ms
Calculating -------------------------------------
Enumerable#select.first
173.654k (± 2.9%) i/s -      3.473M in  20.016201s
Enumerable#detect    788.926k (± 0.6%) i/s -     15.832M in  20.068122s
Comparison:
Enumerable#detect:   788926.2 i/s
Enumerable#select.first:   173654.0 i/s - 4.54x  (± 0.00) slower
```
Test Code
```ruby
require 'benchmark/ips'
ARRAY = [*1..100]
def slow
ARRAY.select { |x| x.eql?(15) }.first
end
def fast
ARRAY.detect { |x| x.eql?(15) }
end
Benchmark.ips(20) do |x|
x.report('Enumerable#select.first') { slow }
x.report('Enumerable#detect') { fast }
x.compare!
end 
``` …

chore: minor refactor from select first to detect

---

.github/workflows/test.yml
lib/carrierwave/downloader/remote_file.rb
spec/downloader/remote_file_spec.rb

Have RemoteFile raise CarrierWave::DownloadError when the HTTP response is of a type that has no content, according to the standards. In those cases, response.body returns nil.
There are 8 response types that have no body, 4 of which we can get, so just check whether the body was nil.
Fixes #2632

Raise DownloadError when no content is returned

---

lib/carrierwave/storage/file.rb
spec/storage/file_spec.rb

Given that it is not advised to put other stuff in the same directory as CarrierWave's cache, this fix makes clean_cache! not break if you do.
Based on the similar fix for the Fog storage clean_cache!.

Local storage clean_cache! fix for off-topic files

---

lib/carrierwave/uploader/configuration.rb
spec/uploader/configuration_spec.rb

- fixes #2417
- Currently, it's not possible to set `false` to some boolean values (e.g. `fog_public`) via in-class configuring.
- There are some workarounds already, but it would be more convenient and intuitive.
- [How to: Define different storage configuration for each Uploader.](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Define-different-storage-configuration-for-each-Uploader.)
- [How to: Secure uploaded file in S3 and make it only accessible by supplying secret token?](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Secure-uploaded-file-in-S3-and-make-it-only-accessible-by-supplying-secret-token%3F)
In `config/initializers/carrierwave.rb` :
```ruby
CarrierWave.configure do |config|
config.fog_public = true
...
end
```
and `avatar_uploader.rb` : …

Enable to override configurations by 'false' on a per-uploader basis

---

lib/carrierwave/mounter.rb

We're currently working on our Ruby 2.7 to 3.0 upgrade and we're testing with deprecation warnings enabled on Ruby 2.7. Most of the warnings we've seen have been related to keyword arguments, but there was a different one coming from Carrierwave:
```
.../carrierwave-1.3.2/lib/carrierwave/mounter.rb:113: warning: deprecated Object#=~ is called on TrueClass; it always returns nil
```
This PR aims to silence that warning with no change in behaviour on any version of Ruby.
Unfortunately I wasn't able to get the tests running in my M1 Mac development environment. It looks like the project has GitHub actions set up so hopefully that will work ok 😄 
Sorry we're still on 1.x 😰 Many thanks to all the maintainers 🙏

Fix Ruby 2.7 deprecation warning on Mounter#remove?

---

README.md
lib/carrierwave/downloader/base.rb
lib/carrierwave/uploader/configuration.rb
spec/downloader/base_spec.rb

https://github.com/carrierwaveuploader/carrierwave/pull/2577 is good change that I wanted.
I'll add a config for download retry wait time.
Since the appropriate wait time depends on the each of the remote server, it is better to be able to configure the wait time on the application side.

Support to configure download retry wait time

---

.github/workflows/test.yml

Ruby 3.2.0 has been released.
https://www.ruby-lang.org/en/news/2022/12/25/ruby-3-2-0-released/

Add Ruby 3.2 to CI matrix

---

README.md

This PR change the year of the license to the first publication date only.

Change the year of the license to the first publication date only

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb
spec/processing/rmagick_spec.rb

- Don't call `each` if `@_mounters` is unitialized or nil. It will be nil for calls to later mounters, or if not referenced or saved.
- Don't interpolate `column` when it should be a local variable.
- Don't define global functions in specs. Make them local to the block.
- Cover more missing scenarios.
- Fix some rubocop failures.
[Fixes #1962]

Fix dup with multiple mounters or not cached

---

lib/carrierwave/mount.rb
lib/carrierwave/mounter.rb
lib/carrierwave/orm/activerecord.rb
lib/carrierwave/uploader/proxy.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/orm/activerecord_spec.rb

This is a proposal for solving ActiveModel::Dirty related issues.
Previously saving an attachment takes following process:
- On attachment assignment: does not assign the attribute value but call `#{column}_will_change!`
- Before save: assign identifier as the attribute value
After this PR, it will be like:
- On attachment assignment: assign temporary identifier as the attribute value (this marks the column as changed, so we don't need to call `#{column}_will_change!`)
- Before save: assign the true identifier as the attribute value
The reason for introducing the idea of _temporary identifier_ is that there are the cases we can't determine the identifier on the attachment assignment - an identifier is made from the filename, but filename [can be overridden to reference another attribute …

Handle assignments in an ActiveModel::Dirty-friendly way

---

lib/carrierwave/storage/fog.rb

Replaces instances of: `@uploader.fog_credentials[:provider]` with it's helper method: `fog_provider`
This proves to be helpful for me because I am trying to build my own Fog provider. In many scenarios, my provider behaves like AWS and in some scenarios it behaves like Google.
Having the ability to monkeypatch a single method: `CarrierWave::Storage::Fog#fog_provider` cleans up my implementation greatly.

Use helper method to access fog_provider

---

README.md
lib/carrierwave/locale/en.yml
lib/carrierwave/uploader.rb
lib/carrierwave/uploader/dimension.rb
spec/uploader/callback_spec.rb
spec/uploader/dimension_spec.rb

Added image dimension validation.
FYI: [How to: Validate image file size · carrierwaveuploader/carrierwave Wiki](https://github.com/carrierwaveuploader/carrierwave/wiki/How-to:-Validate-image-file-size)
```rb
class PhotoUploader < CarrierWave::Uploader::Base
include CarrierWave::MiniMagick
def dimension_ranges
[(1000..), 1000..]
end
end
```

Add image dimension validation

---

lib/carrierwave/storage/file.rb
spec/storage/file_spec.rb

CarrierWave::Storage::File#clean_cache! can't delete cache direcotries if the uploader's root has changed.
This PR fix it.
[Fixes #2113]

Fix #clean_cache! to delete cache dirs under uploader root

---

lib/carrierwave/mounter.rb

Since the release of Ruby 3.2 `Kernel#=~` has been removed. Which that `IntegerClass`, `FalseClass` doesn't respond to `def =~` anymore. 
Since the String class still respond to it we could infer `remove` to a string and keep the same check than before. I'm open a more complicated solution which check all types: `Numeric`, `FalseClass` and `String`

Bugfix: fix Kernel#=~ removal in Ruby 3.2

---

README.md

I've set up a project with carrierwave and fog-google [following the README](https://github.com/carrierwaveuploader/carrierwave/blob/master/README.md#using-google-cloud-storage). And got a deprecation warning message.
```ruby
DEPRECATION WARNING: #fog_provider is deprecated and has no effect (called from block in <main> at /Users/cou929/Desktop/ws-fog/test_carrierwave/config/initializers/carrierwave.rb:4)
```
```ruby
CarrierWave.configure do |config|
config.fog_provider = 'fog/google'
config.fog_credentials = {
provider:               'Google',
google_project:         'my-project',
google_json_key_string: 'xxxxxx'
}
config.fog_directory = 'google_cloud_storage_bucket_name'
end
```
It seems that the `config.fog_provider` [was already deprecated …

remove deprecated configuration from README

---

README.md
lib/carrierwave/uploader/cache.rb
lib/carrierwave/uploader/configuration.rb
lib/carrierwave/uploader/processing.rb
lib/carrierwave/uploader/store.rb
spec/processing/rmagick_spec.rb
spec/uploader/processing_spec.rb
spec/uploader/versions_spec.rb

With the current implementation, CarrierWave does not handle change of the file extension on converting a file. Suppose you have
```ruby
class MyUploader < CarrierWave::Uploader::Base
include CarrierWave::MiniMagick
process convert: :png
end
```
and upload a JPEG file named `test.jpg`, you'll get a PNG format file with the filename of `test.jpg`. This is often not what users want, as they expect the file extension also changes. The existing solution was to override `#filename` to set the desired extension, as suggested like [this](https://stackoverflow.com/a/70703162).
```ruby
class MyUploader < CarrierWave::Uploader::Base
include CarrierWave::MiniMagick
process convert: :png
def filename
super.chomp(File.extname(super)) + '.png' if original_filename.present?
end
end
```
But even with …

[BREAKING CHANGE] Use the resulting file extension on changing format by :convert

---

lib/carrierwave/uploader/processing.rb
spec/uploader/processing_spec.rb

As mentioned in https://github.com/carrierwaveuploader/carrierwave/pull/2636#issuecomment-1437791368, I just cherry-picked the commit to the `2.x-stable` branch and created a new PR to backport it.
Can you please release a new 2.x version with this fix? I'm trying to upgrade to ruby 3.x, but the current stable 2.x version doesn't work with ruby 3.x and there is no stable release yet for carrierwave 3.x.

[backport] fix: ruby 2.7 kwarg warning in uploader process

---

CONTRIBUTING.md

Since #2500, `libvips` is required to run tests.

Mention `libvips` in CONTRIBUTING.md

---

lib/carrierwave/mounter.rb
spec/orm/activerecord_spec.rb

Since v3.0.0, Carrierwave raises `NoMethodError` when a record is rollbacked if uploaders methods don't call at all.
```
NoMethodError:
private method `select' called for nil:NilClass
current_paths = (@removed_uploaders + @uploaders.select(&:staged)).map(&:path)
```
This attempts to fix that error and makes work correctly.

Fix a `NoMethodError` when a record is rollbacked

---

lib/carrierwave/mounter.rb
lib/carrierwave/uploader/store.rb
spec/mount_multiple_spec.rb
spec/mount_single_spec.rb
spec/orm/activerecord_spec.rb
spec/uploader/store_spec.rb

I'm sorry that the deduplication feature introduced in the 3.0 release is completely broken, as reported by #2677. This PR is another attempt to fix it.
The approach is to move the deduplication logic from #store! to `#write_identifier`, which is invoked on before_save thus allowing the modified filename(identifier) to be persisted. To work around the limitation that the deduplication timing can't be made earlier because `#store_dir` relies on the model's id, the scope of deduplication was narrowed down only to filename, instead of whole `#store_path`. This sometimes can lead to unnecessary deduplication in a case like a user decided to use a custom `#store_dir` to handle deduplication by their own, but even if that happens it does not harm data consistency, so I think it's acceptable. …

Fix deduplicated filename not being persisted

---

spec/orm/activerecord_spec.rb

files should not be removed on rollback if not updated
minimum reproducible example for https://github.com/carrierwaveuploader/carrierwave/issues/2685

add failing test for https://github.com/carrierwaveuploader/carrierwave/issues/2685

---

spec/orm/activerecord_spec.rb

I was reading carrierwave codebase and noticed that this test is a complete duplicate of 
https://github.com/carrierwaveuploader/carrierwave/blob/d339c275f49de70547c2e5e6145e72fdfdc6379a/spec/orm/activerecord_spec.rb#L879-L887
confirmed that it was added in this commit https://github.com/carrierwaveuploader/carrierwave/commit/8d98ecd19c043b32c97f7745790def0051de94f8 and seems safe to delete

delete duplicate tests

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

If use :mount_on option and call #dup, it would raise `ActiveModel::MissingAttributeError`
```ruby
class Attachment < ::ApplicationRecord
mount_uploader(:file, FileUploader, mount_on: :stored_filename)
end
attachment.dup
```
Got error:
```
ActiveModel::MissingAttributeError:
can't write unknown attribute `file`
```

fix: call #dup would raise MissingAttributeError while putting :mount_on in options

---

lib/carrierwave/mount.rb
lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

Added a failing test for https://github.com/carrierwaveuploader/carrierwave/issues/2689
duplication should not affect the duplicated objects path.
*Updated*
And now fixes https://github.com/carrierwaveuploader/carrierwave/issues/2689

Fix mounter cache duplication on dup

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

dup should not prevent uploading
fixes https://github.com/carrierwaveuploader/carrierwave/issues/2700

Fix dup mounter cache behavior

---

.github/workflows/test.yml
carrierwave.gemspec
lib/carrierwave/processing/rmagick.rb

This PR targets the `1.x-stable` branch.
* Adding Ruby 3.2 for tests in CI.
* Use latest `rmagick` for Ruby 3.2 as `rmagick 2.16.0` calls the deprecated `rb_obj_tainted`
* Also fix the usage for the newer `rmagick` version to use `::Magick::Image.new(width, height) { |img| img.background_color = ...}` pattern.
More context on why 1.x is still being used: https://github.com/carrierwaveuploader/carrierwave/pull/2640#issuecomment-1323532577.
Would also appreciate if the maintainer could release a new gem for 1.x 🙏

Test against Ruby 3.2 in CI for 1.x

---

lib/carrierwave/mounter.rb
lib/carrierwave/uploader/store.rb
spec/orm/activerecord_spec.rb

fixes https://github.com/carrierwaveuploader/carrierwave/issues/2702
`mark_remove_#{column}_false` is called after commit
https://github.com/rajyan/carrierwave/blob/e53c9c33674289ffabd8aa6ab3160e2ce60872dd/lib/carrierwave/mount.rb#L387-L389
which was the cause of this issue.
Changed to write a temporary identifier only if remove is changed to a truthy value.

Fix dirty handling on update

---

README.md
lib/carrierwave/downloader/base.rb
lib/carrierwave/uploader/configuration.rb
spec/downloader/base_spec.rb

closes https://github.com/carrierwaveuploader/carrierwave/issues/2695
Looking at these issues, a lot of people are looking for a way to disable ssrf filter in testing.
https://github.com/carrierwaveuploader/carrierwave/issues/2695
https://github.com/arkadiyt/ssrf_filter/issues/33
https://github.com/arkadiyt/ssrf_filter/issues/59
https://github.com/carrierwaveuploader/carrierwave/issues/2573
I believe it might worth making `skip_ssrf_protection` configurable.

add skip_ssrf_protection config

---

lib/carrierwave/uploader/store.rb
spec/uploader/store_spec.rb

Context: https://github.com/carrierwaveuploader/carrierwave/issues/2708#issuecomment-1890328537
I'm not totally sure that this is side-effect-free (there can be a legitimate case for #filename not to return value?) , but at least it can be helpful to some people.
I want to hear your opinion.
@y-yagi @RachalCassity @rajyan @ryan-mcneil
Closes #2708, Refs. #2659

Show warning if #filename is safeguarded as in the pre-3.x style

---

README.md
carrierwave.gemspec
lib/carrierwave/processing/mini_magick.rb
lib/carrierwave/processing/rmagick.rb
lib/carrierwave/processing/vips.rb
spec/processing/mini_magick_spec.rb
spec/processing/rmagick_spec.rb
spec/processing/vips_spec.rb

I had a need for this functionality, and while I know I could use the `vips!` method in my uploader it felt like an omission - so I put together a PR with a (passing) spec. The test is a little basic, but I wasn't sure if it would be ok to add new image fixtures, which I would need to do in order to test that the cropping produces the correct output (my test only checks the resulting dimensions). I'd be happy to look at implementing further vips methods if desired!

Added support for the "crop" method.

---

carrierwave.gemspec
lib/carrierwave/downloader/remote_file.rb
spec/processing/rmagick_spec.rb

This [commit](https://github.com/rails/marcel/commit/e413daeffaed05d1e34b31e0ff1de95182d2d418) of the Marcel gem, which has just shipped in version 1.0.3, breaks Carrierwave as the `Marcel::TYPES` constant used [here](https://github.com/carrierwaveuploader/carrierwave/blob/ed8799191824a4d2762eb1028c01220102699377/lib/carrierwave/downloader/remote_file.rb#L36) has been removed.
This PR is to switch to using `Marcel::Magic.new(content_type).extensions` to return the extensions and not use constants.

Use Marcel::Magic.new(content_type).extensions instead of Marcel::TYPES[content_type]

---

lib/carrierwave/uploader/versions.rb
spec/uploader/versions_spec.rb

Because of the restriction that Ruby constant names must always begin with `[A-Z]`, it would be desirable to make sure that this restriction is satisfied when naming dynamic constants.
- Fix https://github.com/carrierwaveuploader/carrierwave/issues/2722
It was implemented well in carrierwave v2, but when `object_id` was removed from the constant name  at https://github.com/carrierwaveuploader/carrierwave/commit/a9de7565eabb4cdca05bb090cdf797eb1720c09c, `Uploader` prefix was also removed at the same time for some reason.

Change version constant naming pattern

---

.github/workflows/test.yml
gemfiles/rails-7-2.gemfile

This PR adds Rails 7.2 to the CI matrix to confirm `carrierwave` working with Rails 7.2.
Currently, the latest Rails runs against only the latest Ruby and the previous Rails version runs against multiple Rubies. So I updated the matrix to follow it.

CI against Rails 7.2

---

README.md

Fixed a minor typo in the README. Changed `al three processing libraries` to `all three processing libraries`.

Fix typo in README: change 'al three' to 'all three'

---

lib/carrierwave/utilities/uri.rb

Because uri > 1.0 switched to RFC3986 as the default parser
Fixes https://github.com/carrierwaveuploader/carrierwave/issues/2759

Use RFC2396_REGEXP explicitly

---

lib/carrierwave/storage/fog.rb
lib/carrierwave/uploader/configuration.rb
spec/storage/fog_helper.rb

S3 endpoints even when ENV['AWS_USE_FIPS_ENDPOINT']=='true'. When FIPS is called for, and we are in a region where FIPS endpoints are available, this method should return the FIPS endpoint.
Furthermore, when S3 Transfer Acceleration (S3TA) is requested by configuration, the above endpoint gets overridden to select the S3TA endpoint. However, S3TA is not avaialble in GovCloud, and has no FIPS endpoint equivalents. In this instance, if the region is a GovCloud region, or if FIPS mode is called for, do not override the endpoint to use S3TA.
This is functionally equivalent to an issue submitted to the fog-aws project.  https://github.com/fog/fog-aws/issues/729

Support AWS S3 FIPS endpoints

---

lib/carrierwave/orm/activerecord.rb
spec/orm/activerecord_spec.rb

While `write_uploader` is [aliased by default](https://github.com/carrierwaveuploader/carrierwave/blob/f0620919d00dbd74d31e6b48f62346d6090e88f7/lib/carrierwave/orm/activerecord.rb#L15) to `write_attribute`, it may be overridden in the model (see example below).
```ruby
class SomeModel < ActiveRecord::Base
store :settings, accessors: [:logo] # virtual column logo
mount_uploader :logo, LogoUploader
def write_uploader(column, identifier)
settings[column.to_sym] = identifier
end
def read_uploader(column)
settings[column.to_sym]
end
end
```
However duplicating such a model fails with the following error.
```ruby
[1] pry(main)> SomeModel.new.dup
ActiveModel::MissingAttributeError: can't write unknown attribute `logo
````
This change ensures that on duplication, the override `write_uploader` …

Fix #dup with custom serialisation

---

lib/carrierwave/processing/mini_magick.rb

Fixes #2732
Starting in Alpine Linux 3.19, installing the `imagemagick` package no longer includes support for JPG, SVG, and other image formats. Additional packages must be installed to support each image format[1].
This means upgrading Alpine linux on a server can cause Carrierwave to start failing with `CarrierWave::ProcessingError` when uploading images.
The root cause isn't obvious from this error.
However when ImageMagick is not installed, Carrierwave raises `MiniMagick::Error` instead of `CarrierWave::ProcessingError`, and includes the detailed error message.
This PR also raises `MiniMagick::Error` if ImageMagick is installed but is missing the delegates required for the image format being manipulated. This will make it easier to debug when uploads are failing.
I see there was a …

Raise MiniMagick::Error if ImageMagick is missing delegates needed for image formats

---

lib/carrierwave/sanitized_file.rb

mb_chars has been deprecated. and can be replaced by simply removing the method.
cf : https://github.com/rails/rails/pull/54081

Remove use of deprecated mb_chars method
