carrierwaveuploader/carrierwave

.travis.yml
CONTRIBUTING.md
spec/support/activerecord.rb

Here's an attempt to fix build failures on the CI.
Let's see if it works... :pray:

PostgreSQL on Travis

---

carrierwave.gemspec
spec/processing/magic_mime_types_spec.rb
spec/spec_helper.rb

Fix JRuby build for magic mime type

---

README.md

borrowed from react-rails gem.

Squelch the confusion with a big disclaimer

---

CONTRIBUTING.md

I needed to run `brew install libmagic` to get `ruby-filemagic` to install.

Another dependency

---

lib/carrierwave/storage/fog.rb

I modified a few files to hopefully make things more clear and/or get rid of duplications.  Let me know what thoughts are on this!

Small refactors on code

---

lib/carrierwave/mounter.rb
lib/carrierwave/uploader/cache.rb

The diff is a little funky...  but the only modifications are using guard clauses to return early from a method if the body's condition is not met.

Guard clauses for a couple spots

---

lib/carrierwave/orm/activerecord.rb

Rename (column -> mount_on)_will_change! in ActiveRecord

---

lib/carrierwave/error.rb
lib/carrierwave/uploader/configuration.rb
spec/uploader/configuration_spec.rb

Better storage error

---

lib/carrierwave/locale/id.yml

Add locale for Bahasa Indonesia (Indonesian)

add Indonesian locale

---

features/support/activerecord.rb

Fix Cucumber warnings about Rails 4.2 depreciations

---

lib/carrierwave/storage/fog.rb
spec/storage/fog_spec.rb

Resolves #1828, see for history.
Updated specs to accompany change, updated commit name.

Replace URI.decode with CGI.unescape

---

spec/orm/activerecord_spec.rb

fix spec typo

---

CHANGELOG.md

Congrats on your first release in over two years! Time for 1.0? (just teasing)

Update changelog, clarify that 0.11 has been released

---

.travis.yml

Add Ruby 2.3.0 to the build

---

spec/compatibility/paperclip_spec.rb
spec/generators/uploader_generator_spec.rb
spec/mount_multiple_spec.rb

Hello, long time no see!
In order to keep improving carrierwave, I thought about daily improvements I could do to it and concluded that one could be rewriting all the specs to fit the new style from rspec.
I'll keep everything in this PR and will merge by batches. I'll squash each refactor batch in one commit.
Feel free to give any feedback on style or anything.

Refactoring specs

---

lib/carrierwave/locale/el.yml
lib/carrierwave/locale/en.yml
lib/carrierwave/locale/fr.yml

Backport content type whitelist/blacklist translations

---

README.md

The programming school I work uses carrierwave, and this is an issue we get regularly with students, who want to check if a photo was uploaded or not to the model through an 'if' statement. 
The answer is surprisingly hard to find online, it's a hard one to guess at first glance, and I believe adding it to the readme would help a lot of people.

Added a section in the readme to check for presence of file

---

README.md

I thought it would be cool to explain how to write a conditional method just a little bit more.

Edit readme: clarify writing conditional methods

---

spec/support/activerecord.rb
spec/uploader/extension_whitelist_spec.rb

Remove warnings from specs

---

README.md

Using the master branch is not required anymore.

Fix README for multiple file uploads

---

README.md

As specified in the fog-google README https://github.com/fog/fog-google/blob/master/README.md

Update dependency version constraints

---

README.md

Also added a reference to the associated `carrierwave-i18n` library.

Update locales to current master

---

README.md

- more robust explanation of resizing images.
- explained alternative option of resize_to_fill which crops.

Corrected explanation of option resize_to_fit

---

README.md

Fixed typo from 'copping' to 'cropping'.

---

README.md

Update ```rake db:migrate``` reference to ```rails db:migrate```

Update rake reference to rails

---

lib/carrierwave/sanitized_file.rb

I've refactored `path` method in `carrierwave/sanitized_file.rb`.
Please review this patch!
Thank you.

Small refactor

---

lib/carrierwave/mounter.rb
lib/carrierwave/sanitized_file.rb
lib/carrierwave/uploader/cache.rb
lib/carrierwave/uploader/download.rb
lib/carrierwave/uploader/store.rb
lib/carrierwave/uploader/url.rb

Hi!
I've refactored some conditional expressions as below.
- ```and``` -> ```&&```
- ```or``` -> ```||```
- ```not``` -> ```!```
- ```hoge == ""``` -> ```hoge.blank?```
- ```hoge == 0``` -> ```hoge.zero?```
Please review this PR.
Thank you.

Refactor some conditional expressions

---

README.md

Conditional version was written, but conditional process was not in README.

Add conditional process in README

---

carrierwave.gemspec
lib/carrierwave/sanitized_file.rb
spec/sanitized_file_spec.rb

- Replace `mimemagic` with `marcel` gem
- Resolves #2548
Waiting for https://github.com/rails/marcel/pull/30 to be merged to add the correct `marcel` version

Replace mimemagic with marcel gem

---

lib/carrierwave/storage/fog.rb

Fix typo in google config

---

lib/carrierwave/uploader/processing.rb
spec/uploader/processing_spec.rb

fix: ruby 2.7 kwarg warning in uploader process

---

features/versions_overridden_filename.feature
spec/downloader/base_spec.rb
spec/mount_multiple_spec.rb
spec/processing/mini_magick_spec.rb
spec/processing/rmagick_spec.rb
spec/processing/vips_spec.rb
spec/sanitized_file_spec.rb
spec/spec_helper.rb
spec/storage/file_spec.rb
spec/uploader/cache_spec.rb

This PR is fix some typos.
- s/filaname/filename/
- s/sybmols/symbols/
- s/iamges/images/
- s/integity/integrity/
- s/enforece/enforce/
- s/Santized/Sanitized/
- s/exsting/existing/
- s/compartibility/compatibility/

Fix some typos

---

lib/generators/templates/uploader.rb.erb

Add CarrierWave::Vips comment to uploader template
